INSERT INTO `fygodb`.`transaction_type`
(
`transaction_type_nm`,
`description`,
`created_dt`,
`created_by`,
`last_modified_dt`,
`last_modified_by`)
VALUES

(
'payment',
'customer can pay using debitcard','2018-02-05','dhanu',
'2018-02-06',
'rajendra');

INSERT INTO `fygodb`.`transaction_type`
(
`transaction_type_nm`,
`description`,
`created_dt`,
`created_by`,
`last_modified_dt`,
`last_modified_by`)
VALUES

(
'refund',
'customer refund through phonepe','2018-03-07','kiran',
'2018-03-08',
'hari');

